### ISSUE TITLE
Sonos Beam has been added and causes error

### ISSUE THREAD

**Issue by phoniclynx** [duncan3dc/sonos#84] opened 2018-07-25 04:38 UTC
I have just added a Sonos Beam to the family and gone to check everything now that it has been set up and is working.

I believe I have it clearing the cache by stating:
`$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);`
but when I go to get the alarms I get an error in regards to the SOAP discovery:

> Fatal error:  Call to a member function soap() on null in /var/www/html/vendor/duncan3dc/sonos/src/Network.php on line 593

When I do a print_r($sonos) I get the response:
```
duncan3dc\Sonos\Network Object
(
    [speakers:protected] => 
    [playlists:protected] => 
    [alarms:protected] => 
    [cache:protected] => Doctrine\Common\Cache\ArrayCache Object
        (
            [data:Doctrine\Common\Cache\ArrayCache:private] => Array
                (
                )

            [hitsCount:Doctrine\Common\Cache\ArrayCache:private] => 0
            [missesCount:Doctrine\Common\Cache\ArrayCache:private] => 0
            [upTime:Doctrine\Common\Cache\ArrayCache:private] => 1532493331
            [namespace:Doctrine\Common\Cache\CacheProvider:private] => 
            [namespaceVersion:Doctrine\Common\Cache\CacheProvider:private] => 
        )
    [logger:protected] => Psr\Log\NullLogger Object
        (
        )
    [multicastAddress:protected] => 239.255.255.250
    [networkInterface:protected] => 
)
```

Any idea what I can do to fix this?

**Comment by duncan3dc** [comment] 2018-07-25 06:04
Hi @phoniclynx, please can you enable logging and send the output.

I'll need the device details to add support for it for you :+1:

**Comment by phoniclynx** [comment] 2018-07-25 06:10
This is the output of the logger:

```
[2018-07-25 15:39:51] sonos.INFO: creating speaker instances [] []
[2018-07-25 15:39:51] sonos.INFO: discovering devices... [] []
[2018-07-25 15:39:51] sonos.DEBUG: M-SEARCH * HTTP/1.1 HOST: 239.255.255.250:reservedSSDPport MAN: ssdp:discover MX: 1 ST: urn:schemas-upnp-org:device:ZonePlayer:1  [] []
[2018-07-25 15:39:52] sonos.DEBUG: HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.213:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54281 (ZPS13) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_7828CAC16B8C01400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 28 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.233:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54281 (ZPS14) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_949F3ED018C401400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 3 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.220:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54230 (BR200) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_7828CA70079C01400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 14 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 1 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.214:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54281 (ZPS13) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_7828CAC16B4201400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 31 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.188:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54230 (ANVIL) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_949F3EA0752201400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 23 X-RINCON-PROXY: RINCON_949F3ED018C401400 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.51:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54281 (ZPS6) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_5CAAFD0B467801400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 258 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://192.168.0.50:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/44.2-54281 (ZPS6) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_5CAAFD09469C01400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT X-RINCON-BOOTSEQ: 201 X-RINCON-WIFIMODE: 0 X-RINCON-VARIANT: 2 HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ   [] []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.213:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54281 (ZPS13)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_7828CAC16B8C01400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"28","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.233:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54281 (ZPS14)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_949F3ED018C401400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"3","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.220:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54230 (BR200)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_7828CA70079C01400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"14","x-rincon-wifimode":"0","x-rincon-variant":"1","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.214:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54281 (ZPS13)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_7828CAC16B4201400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"31","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.188:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54230 (ANVIL)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_949F3EA0752201400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"23","x-rincon-proxy":"RINCON_949F3ED018C401400","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.51:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54281 (ZPS6)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_5CAAFD0B467801400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"258","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ"} []
[2018-07-25 15:39:52] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://192.168.0.50:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/44.2-54281 (ZPS6)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_5CAAFD09469C01400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT","x-rincon-bootseq":"201","x-rincon-wifimode":"0","x-rincon-variant":"2","household.smartspeaker.audio":"Sonos_HF0QBaU1NZuQEq50M5GJ0FOMtT.rKzcXtW6wnJ8kiaIG8DZ"} []
[2018-07-25 15:39:52] sonos.NOTICE: Getting topology info from: http://192.168.0.213:1400/status/topology [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.213:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.213 model: S13 [] []
[2018-07-25 15:39:52] sonos.INFO: getting xml from cache: http://192.168.0.213:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.233:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.233 model: S14 [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.220:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.220 model: BR200 [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.214:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.214 model: S13 [] []
[2018-07-25 15:39:52] sonos.INFO: getting xml from cache: http://192.168.0.214:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.188:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.188 model: Sub [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.51:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.51 model: S6 [] []
[2018-07-25 15:39:52] sonos.INFO: getting xml from cache: http://192.168.0.51:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.NOTICE: requesting xml from: http://192.168.0.50:1400/xml/device_description.xml [] []
[2018-07-25 15:39:52] sonos.DEBUG: 192.168.0.50 model: S6 [] []
[2018-07-25 15:39:52] sonos.INFO: getting xml from cache: http://192.168.0.50:1400/xml/device_description.xml [] []
```

**Comment by duncan3dc** [comment] 2018-07-25 06:13
Thanks very much, I'll take a look at adding support tonight for you.
In the meantime please update to version [2.0](http://duncan3dc.github.io/sonos/v2/) as this is the supported version now

**Comment by phoniclynx** [comment] 2018-07-25 07:11
How do I check which version I am running? When I ask composer to update it says there is nothing to update?

```
 php composer.phar update duncan3dc/sonos
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by duncan3dc** [comment] 2018-07-25 07:14
Which version of PHP are you on? Only PHP 7.1 is under [active support](http://php.net/supported-versions.php), composer won't provide 2.0 unless you're on at least 7.1

**Comment by phoniclynx** [comment] 2018-07-25 08:46
PHP Version 5.6.33-0+deb8u1

**Comment by duncan3dc** [comment] 2018-07-25 10:03
Ok you'll want to update your PHP version to at least 7.1, there's a blog post below that has some details for Debian:
https://www.colinodell.com/blog/201612/installing-php-71

**Comment by phoniclynx** [comment] 2018-07-25 12:54
okay.. after many hours of installing the new version of Linux, because I have a Raspberry-PI.. it wasn't quite so straightforward: I've gone install your package again... but I'm stuck on this error with composer:

```
php composer.phar require duncan3dc/sonos
Using version ^2.0 for duncan3dc/sonos
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for psr/log (locked at 1.0.2) -> satisfiable by psr/log[1.0.2].
    - duncan3dc/sonos 2.0.0 requires duncan3dc/logger-aware-trait ^0.1.0 -> satisfiable by duncan3dc/logger-aware-trait[0.1.0].
    - duncan3dc/sonos 2.0.1 requires duncan3dc/logger-aware-trait ^0.1.0 -> satisfiable by duncan3dc/logger-aware-trait[0.1.0].
    - duncan3dc/logger-aware-trait 0.1.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Conclusion: don't install psr/log 1.0.0
    - Installation request for duncan3dc/sonos ^2.0 -> satisfiable by duncan3dc/sonos[2.0.0, 2.0.1].


Installation failed, reverting ./composer.json to its original content.

```

I don't quite know where to go from here? I don't know what logger-aware is?

**Comment by phoniclynx** [comment] 2018-07-25 13:02
I managed to get psr/log installed (somehow by installing duncan3dc/logger-aware-trait) but I still get the last 3 lines as an error:

```
Using version ^2.0 for duncan3dc/sonos
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - duncan3dc/sonos 2.0.1 requires duncan3dc/logger-aware-trait ^0.1.0 -> satisfiable by duncan3dc/logger-aware-trait[0.1.0] but these conflict with your requirements or minimum-stability.
    - duncan3dc/sonos 2.0.0 requires duncan3dc/logger-aware-trait ^0.1.0 -> satisfiable by duncan3dc/logger-aware-trait[0.1.0] but these conflict with your requirements or minimum-stability.
    - Installation request for duncan3dc/sonos ^2.0 -> satisfiable by duncan3dc/sonos[2.0.0, 2.0.1].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by duncan3dc** [comment] 2018-07-25 20:01
I've just released version 2.0.2 that should fix both of your issues, can you try that?

If you're still having problems, please post your `composer.json`, and the `composer` command you are running

**Comment by phoniclynx** [comment] 2018-07-25 20:54
That looks a tad better:

```
php composer.phar require duncan3dc/sonos
Using version ^2.0 for duncan3dc/sonos
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 1 update, 0 removals
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing duncan3dc/cache (0.6.1): Downloading (100%)
  - Updating duncan3dc/sonos (1.9.11 => 2.0.2): Downloading (100%)
Writing lock file
Generating autoload files
```

I just tried to run it.. but it doesn't seem to be doing anything within PHP at all.

I have work today (13 hrs) I will check it out more. Everything got changed during the upgrade for the Rasp Pi... so don't know where to look just atm.

**Comment by duncan3dc** [comment] 2018-07-25 20:57
Great, so the latest version has installed, and your script is not falling over because of the Beam anymore.

If you can send me your script I can give you any pointers on things you've missed with the 2.0 upgrade

**Comment by phoniclynx** [comment] 2018-07-26 10:09
My code is as follows:

```
function sonosAlarmUpdate($id, $time, $active, $volume = NULL){
	$sonos = new Network(new \Doctrine\Common\Cache\ArrayCache);
	
	$logger = new \Monolog\Logger("sonos");
	$handler = new \Monolog\Handler\StreamHandler("php://output", \Monolog\Logger::DEBUG);
	$logger->pushHandler($handler);
	$sonos->setLogger($logger);
	
	print_r($sonos);
	
	$alarms = $sonos->getAlarms();
	echo "<pre>";
	print_r($alarms);
	echo "</pre>";
	$alarm = $sonos->getAlarmById($id);
	$alarm->setTime("$time");
	
	if(!$volume) $volume = $alarm->getVolume();
	
	if (!$active) {
		$alarm->deactivate();
		$alarm->once();
	} else {
		$alarm->activate();
		$alarm->once();
		$alarm->setVolume($volume);
	}
}
```

This is currently printing nothing (even with those print_r 's

**Comment by duncan3dc** [comment] 2018-07-26 10:36
If it's printing nothing then you must have PHP configured to hide errors.

But the first thing I notice is your constructor is passing a doctrine cache instance, you should remove that and just use: `$sonos = new Network();`

Also you'll need to parse your alarm time to a `\duncan3dc\Sonos\Utils\Time` instance:
```php
$alarm->setTime(Time::parse($time));
```

Try that and let me know how you get on. If you're still getting a blank screen try [this help](https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display) for enabling errors

**Comment by phoniclynx** [comment] 2018-07-26 10:40
ahh.. that's becuase I accidently set the wrong php.ini file.. however I have some more information for you: I am getting this error now:

```
Fatal error:  Uncaught TypeError: Argument 1 passed to duncan3dc\Sonos\Network::__construct() must be an instance of duncan3dc\Sonos\Interfaces\Devices\CollectionInterface or null, instance of Doctrine\Common\Cache\ArrayCache given, called in /var/www/html/sonoscontroller.php on line 12 and defined in /var/www/html/vendor/duncan3dc/sonos/src/Network.php:53
Stack trace:
#0 /var/www/html/sonoscontroller.php(12): duncan3dc\Sonos\Network->__construct(Object(Doctrine\Common\Cache\ArrayCache))
#1 /var/www/html/GoogleAlarm/quickstart.php(260): sonosAlarmUpdate('14', '16:19', false, '10')
#2 {main}
  thrown in /var/www/html/vendor/duncan3dc/sonos/src/Network.php on line 53

```

**Comment by duncan3dc** [comment] 2018-07-26 10:50
You need to import the time class with a `use` statement, or use a fully qualified version (instead of just `Time`).

```php
use duncan3dc\Sonos\Utils\Time;

# or

\duncan3dc\Sonos\Utils\Time::parse($time);
```

**Comment by phoniclynx** [comment] 2018-07-26 10:51
OK... figured that out just as you posted that... however.. it SET the time.. but set it in the alarm incorrectly.. it set it to 0016 when it was supposed to be 1619

**Comment by duncan3dc** [comment] 2018-07-26 11:00
Ok, please can you log that as a separate issue, with a script to reproduce and I'll investigate it for you.

This issue with the Beam is fixed now :+1:

**Closed by duncan3dc** 2018-07-26 11:00 UTC
Labels: enhancement
