### ISSUE TITLE
Soap-Request loop when trying to get more tracks from queue than avaliable

### ISSUE THREAD

**Issue by Tobseb** [duncan3dc/sonos#54] opened 2016-10-04 17:40 UTC
I get the following soap-request-loop when trying to get more tracks from a queue than available.

I am just using the following code:
`$queue->getTracks($state->queueNumber + 1, 4)`

Because the doc say "The **maximum** number of tracks to return" I expected not to check manually whether the queue is that long or not.

> [2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":11,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":15,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":19,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":23,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":27,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":31,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":35,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":39,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":43,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-04 17:34:50] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":47,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []

**Comment by Tobseb** [comment] 2016-10-04 17:42
The problem clearly is this loop - Queue.php (line 138 to 149). Line 149 says it would only stop trying to get further (non-existent) tracks if there are more. But obviously there aren't..

`do {
            $data = $this->browse("DirectChildren", $start, $limit);
            $parser = new XmlParser($data["Result"]);
            foreach ($parser->getTags("item") as $item) {
                $tracks[] = $this->trackFactory->createFromXml($item);
                if ($total > 0 && count($tracks) >= $total) {
                    return $tracks;
                }
            }

            $start += $limit;
        } while ($data["TotalMatches"] && count($tracks) < $data["TotalMatches"]);`

**Comment by duncan3dc** [comment] 2016-10-04 17:43
Thanks @Tobseb, I'll take a look

**Comment by duncan3dc** [comment] 2016-10-04 18:51
Just for clarity, the issue isn't the number of tracks requested, it's the start position.

Asking `getTracks()` to start from a position in the queue that does not exist causes an infinite loop.

I've added a fix for this to [1.9.3](https://github.com/duncan3dc/sonos/releases/tag/1.9.3) available now

**Closed by duncan3dc** 2016-10-04 18:51 UTC
Labels: bug

**Comment by Tobseb** [comment] 2016-10-05 11:03
@duncan3dc I had a look into it. For me it's no longer a loop out of infinite requests now, but there is still one unnecessary request if the queue is not that long.

Use the following example with a queue of 12 titles (so index 0 to 11).

> [2016-10-05 10:56:37] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":10,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []
[2016-10-05 10:56:37] sonos.INFO: sending soap request to: http://192.168.0.16:1400/MediaServer/ContentDirectory/Control {"BrowseFlag":"BrowseDirectChildren","StartingIndex":14,"RequestedCount":4,"Filter":"","SortCriteria":"","ObjectID":"Q:0"} []

The first request only get's two (of four requested) results so the loop-logic tries to re-request but with a higher starting-index. That simply does not make any real sense.

My issue definitely is that the queue is shorter than the requested amount of tracks.

**Comment by duncan3dc** [comment] 2016-10-05 11:27
Yeh I noticed that after I released last night, I'll take a look at removing the redundant final request when I get a minute
