### ISSUE TITLE
getGroup() is empty

### ISSUE THREAD

**Issue by tomsommer** [duncan3dc/sonos#90] opened 2018-09-07 18:46 UTC
2.0.2, Sonos Version: 9.1 (build 45156150)

```
$devices = new \duncan3dc\Sonos\Devices\Discovery();
$sonos = new Network($devices);
$controller = $sonos->getControllerByRoom('Bedroom');
$tvSpeaker = $sonos->getSpeakerByRoom('TV');

var_dump($tvSpeaker->getGroup(), $controller->getGroup());
var_dump($tvSpeaker->getGroup() === $controller->getGroup());
```

`$tvSpeaker->getGroup()`  is empty: `string(0) ""` sometimes, even though it is in a group with the controller, and the `getGroup()` on the controller returns a value.

**Comment by tomsommer** [comment] 2018-10-04 17:28
With two groups playing at the same time:

```
 $devices = new \duncan3dc\Sonos\Devices\Discovery();
                                $sonos = new Network($devices);

foreach($sonos->getSpeakers() as $_x ) {
var_dump($_x->getName(), $_x->getGroup());
}
```

string(24) "192.168.1.20 - Sonos One"
string(0) ""
string(27) "192.168.1.13 - Sonos Play:3"
string(24) "RINCON_5CAAFD1FFB4F01400"
string(27) "192.168.1.12 - Sonos Play:1"
string(0) ""
string(24) "192.168.1.10 - Sonos One"
string(24) "RINCON_5CAAFD1FFB4F01400"
string(28) "192.168.1.16 - Sonos Playbar"
string(24) "RINCON_5CAAFD1FFB4F01400"
string(27) "192.168.1.17 - Sonos Play:1"
string(0) ""
string(27) "192.168.1.14 - Sonos Play:3"
string(24) "RINCON_5CAAFD1FFB4F01400"
string(23) "192.168.1.9 - Sonos One"
string(24) "RINCON_5CAAFD1FFB4F01400"
string(27) "192.168.1.11 - Sonos Play:1"
string(24) "RINCON_5CAAFD1FFB4F01400"

doing `getControllers` only returns one controller, the Playbar

**Comment by duncan3dc** [comment] 2018-10-24 13:05
Hi @tomsommer, I'm able to reproduce this with a stereo pair of speakers I have, it looks like when a speaker is part of pair, only one of them reports their group. Is that what you are seeing?

**Comment by duncan3dc** [comment] 2018-10-24 14:35
I've put in a fix for this in version [2.0.4](https://github.com/duncan3dc/sonos/releases/tag/2.0.4)

**Closed by duncan3dc** 2018-10-24 14:35 UTC
Labels: bug

**Comment by tomsommer** [comment] 2018-10-24 17:59
Seems "fixed"

**Comment by duncan3dc** [comment] 2018-10-25 08:28
Awesome, thanks for confirming
