### ISSUE TITLE
URI in place of title on play playlist

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#18] opened 2015-04-16 17:08 UTC
Hi,

First, thank for your work it's amazing !!!! 
It's perfectly work for me exept when I aad track of playlist to queue it's work but I get uri in track title in place of real title and no artist, no album no thumbnail....

**Comment by duncan3dc** [comment] 2015-04-16 21:33
Do you have some sample code? Or a uri you are adding?

**Comment by zoic21** [comment] 2015-04-17 07:13
Yes here my code : 
````
$queue = $controller->getQueue();
$playlist = $sonos->getPlaylistByName('test');
if ($playlist == null) {
	throw new Exception('Playlist non trouvé : test');
}
$tracks = $playlist->getTracks();
$queue->clear();
$queue->addTracks($tracks);
$controller->play();
````

And result in queue : 
![capture](https://cloud.githubusercontent.com/assets/1536036/7197486/fb270288-e4e1-11e4-8516-7eb7b50d5167.PNG)

**Comment by 889laurent** [comment] 2015-04-28 13:46
I have the same problem

**Comment by duncan3dc** [comment] 2015-04-29 12:11
Sorry for the delay.

What is the source of those tracks @zoic21? Eg, Spotify, Rdio, etc

**Comment by 889laurent** [comment] 2015-04-29 12:15
in my case deezer source

**Comment by zoic21** [comment] 2015-04-29 13:01
For me it's google music

**Comment by duncan3dc** [comment] 2015-05-30 12:26
Thanks to @mahlstrom this is fixed in version 1.3.1

**Closed by duncan3dc** 2015-05-30 12:26 UTC
Labels: enhancement

**Comment by zoic21** [comment] 2015-05-30 13:22
It's not OK for me, with fix of mahlstrom on version 1.2.0 it's ok but in 1.3.1 same issue

**Comment by duncan3dc** [comment] 2015-05-30 13:32
Sorry @zoic21, if you try `1.3.2` it should be all good

**Comment by zoic21** [comment] 2015-05-30 14:24
It's ok now, thank

**Comment by 889laurent** [comment] 2015-06-14 20:10
with list under deeper on version 1.3.5 the problem is present 
![capture d ecran 2015-06-14 a 22 06 54](https://cloud.githubusercontent.com/assets/8254672/8150236/0fcbc7a4-12e2-11e5-91fa-f56fbe011a2c.png)

**Comment by 889laurent** [comment] 2015-06-15 11:31
its deezer , no deeper ! sorry
